### ISSUE TITLE
How can I hide a sepecific menu item?

### ISSUE THREAD

**Issue by ghost** [arifwidip/mobilemenu#8]
Hi, is there any way to hide a certain menu item which I don't want it to display on the mobile, but I still want it to display on the desktop version. Thanks!

**Comment by arifwidip** [comment]
I think it's not necessary, you can do that with help of CSS3 selector `:nth-child()`. Here i give you an example,

``` css
@media (max-width: 767px) {
  .menu li:nth-child(2) {
    display: none
  }
}
```
